#ifndef AUTO_SOFTWARE_TEST_GLOBALVAR_H_
#define AUTO_SOFTWARE_TEST_GLOBALVAR_H_
enum ENUM_KEYWORD{ FOR = 257, DO, WHILE, IF, ELSE, SWITCH, CASE, BREAK,DEFAULT,CONTINUE,
	TRUE, FALSE, INT,CHAR, BOOL, DOUBLE, VOID, ID,NUM, ASSIGN,
	EQ,NEQ, NE, GE, LE, GT, LT, LOR, XOR, OR, LAND, AND, INC,
	DEC, ADD, SUB, MUL, DIV, MOD, FILEEOF };
#endif // !AUTO_SOFTWARE_TEST_GLOBALVAR_H_

